### ISSUE TITLE
vector-0.13 not allowed

### ISSUE THREAD

**Issue by ysangkok** [folivetti/srtree#2]
see

* https://github.com/commercialhaskell/stackage/issues/6624

**Comment by folivetti** [comment]
I changed package.yaml to allow this new version of vector. Let me know if that fails.

**Comment by ysangkok** [comment]
Thank you! It would be useful to get this change exposed to users on Hackage using a revision. See [Hackage Metadata Revisions - What they are, how they work](https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md#hackage-metadata-revisions--what-they-are-how-they-work)

**Comment by ysangkok** [comment]
By the way, it would be best to also run `hpack` and commit the new `cabal` file, since otherwise cabal will not see the new bound. Cabal doesn't understand `package.yaml` files, only stack does.

**Comment by folivetti** [comment]
thanks for pointing that out. I'm rather new with packaging haskell libraries :-)

I'm currently changing this library and gonna release a new major version soon (in hackage as well)

**Comment by ysangkok** [comment]
Excellent! Feel free to tag me if you have any questions.
