### ISSUE TITLE
Don't use `<=` for upper bounds

### ISSUE THREAD

**Issue by ysangkok** [folivetti/srtree#4]
Apparently, any `.0` appended to a version actually makes the version number bigger than if it wasn't there:

```
% cabal repl -b srtree -c 'vector==0.13.0.0' -w ghc-9.4.4
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: fake-package-0 (user goal)
[__1] trying: srtree-1.0.0.0 (dependency of fake-package)
[__2] next goal: vector (dependency of srtree)
[__2] rejecting: vector-0.13.0.0 (conflict: srtree => vector>=0.12 && <=0.13)
```

So It is best to just avoid `<=` since it would behave wrongly with minor version updates even if the additional `.0` didn't have an effect (which it does).

See https://pvp.haskell.org/

**Comment by folivetti** [comment]
Fixed in https://github.com/folivetti/srtree/commit/ab5b7bea5b017d1850d7b7bc64a88775c7da33d4
